routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::middleware('admin.guest')->group(function (){
    Route::get('/' , 'LoginController@form')->name('login.form');
    Route::post('/' , 'LoginController@attempt')->name('login');
});

Route::middleware('admin.connected')->group(function (){
    Route::get('dashboard' , 'DashboardController@index')->name('dashboard');

    Route::get('logout' , function (){
        \Illuminate\Support\Facades\Auth::guard('admin')->logout();
        return redirect()->route('admin.login.form');
    })->name('logout');
    Route::resources([
        'items' => 'ItemsController',
        'offers' => 'OffersController',
        'users' => 'UsersController',
        'reservations' => 'ReservationsController'
    ]);
    Route::resource('settings' , 'SettingsController')->only('index' , 'update');
    Route::get('/items/activate/{id}' , 'ItemsController@activate')->name('items.activate');
    Route::get('/offers/activate/{id}' , 'OffersController@activate')->name('offers.activate');
    Route::get('/offers/sponsor/{id}' , 'OffersController@sponsored')->name('offers.sponsor');
    Route::get('/reservations/read/{id}' , 'ReservationsController@toggleRead')->name('reservations.read');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::namespace('Landing')->group(function (){
    Route::get('/','OffersController@index')->name('landing.index');
    Route::get('offers/{type?}','OffersController@index')->name('landing.type');
    Route::group(['prefix' => 'offers' ,'as' => 'landing.'] , function (){
        Route::get('show/{id}' , 'OffersController@show')->name('show');
        Route::post('search' , 'OffersController@search')->name('search');
        Route::post('query' , 'OffersController@query')->name('query');
    });
    Route::resource('comments' , 'CommentsController')->only('store');
    Route::resource('impressions' , 'ImpressionsController')->only('store');
});

Route::middleware('guest') ->group(function (){
    Route::view('login' , 'clients.login')->name('login.form');
    Route::post('login' , 'Auth\LoginController@attempt')->name('login');
    Route::view('register' , 'clients.register')->name('register.form');
    Route::post('register' , 'Auth\RegisterController@attempt')->name('register');
});
Route::get('logout' , function (){
    \Illuminate\Support\Facades\Auth::logout();
    return redirect('/');
})->name('logout');

app/Http/Controllers/Admin/ItemsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Contracts\IItems;
use App\Http\Controllers\Controller;
use App\Http\Requests\Entries\ItemsRequest;
use Illuminate\Http\Request;

class ItemsController extends Controller
{
    private $items;

    public function __construct(IItems $items)
    {
        $this->items = $items;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.items.index' , ['items' => $this->items->list()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.items.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ItemsRequest $request)
    {
        $this->items->create($request->all() , $request->file('avatar') , $request->file('cover'));
        return redirect()->route('admin.items.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('admin.items.show' , ['item' => $this->items->find($id) ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return  view('admin.items.edit' , ['item' => $this->items->find($id)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ItemsRequest $request, $id)
    {
        $this->items->update($id , $request->all() , $request->file('avatar') , $request->file('cover'));
        return redirect()->route('admin.items.show' , ['item' => $id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->items->delete($id);
        return  redirect()->route('admin.items.index');
    }

    public function activate(int $id){
        $this->items->activate($id);
        return redirect()->route('admin.items.show' , ['item' => $id]);
    }
}

resources/views/admin/items/create.blade.php
    @php $link = 'items';@endphp
    @extends('admin.layout')
    @section('title') New Item @endsection

@section('content')
    <div class="d-flex justify-content-end">
        <button form="store" class="btn btn-primary btn-sm mr-2"><i class="fa fa-save"></i></button>
    </div>
    <form action="{{ route('admin.items.store') }}" method="post" id="store" enctype="multipart/form-data">
        @csrf
        <div class="card mt-2">
            <div class="card-header">
                <h5 class="card-title">General</h5>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Name:</label>
                            <input type="text" name="name" value="{{ old('name') }}" class="form-control @error('name') is-invalid @enderror">
                            @error('name') <small class="text-danger">{{ $message }}</small> @enderror
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>City</label>
                            <select name="city" class="form-control select2bs4 @error('city') is-invalid @enderror" style="width: 100%;">
                                <option selected disabled>City</option>
                                <option {{ old('city') == 'casa' ? 'selected' : '' }} value="casa"> Casablanca</option>
                                <option {{ old('city') == 'marrakech' ? 'selected' : '' }} value="marrakech"> Marrakech</option>
                                <option {{ old('city') == 'rabat' ? 'selected' : '' }} value="rabat"> Rabat</option>
                                <option {{ old('city') == 'tangier' ? 'selected' : '' }} value="tangier"> Tanger</option>
                                <option {{ old('city') == 'agadir' ? 'selected' : '' }} value="agadir"> Agadir</option>
                                <option {{ old('city') == 'fes' ? 'selected' : '' }} value="fes"> Fes</option>
                                <option {{ old('city') == 'ouarzazate' ? 'selected' : '' }} value="ouarzazate"> Ouarzazate</option>
                                <option {{ old('city') == 'essaouira' ? 'selected' : '' }} value="essaouira"> Essaouira</option>
                            </select>
                            @error('city') <small class="text-danger">{{ $message }}</small> @enderror
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Type</label>
                            <select name="type" class="form-control select2bs4 @error('type') is-invalid @enderror" style="width: 100%;">
                                <option selected disabled>Type</option>
                                <option {{ old('type') == 'activities' ? 'selected' : '' }} value="activities"> Activité</option>
                                <option {{ old('type') == 'restaurants' ? 'selected' : '' }} value="restaurants"> Restaurant</option>
                                <option {{ old('type') == 'hotels' ? 'selected' : '' }} value="hotels"> Hôtel</option>
                                <option {{ old('type') == 'health' ? 'selected' : '' }} value="coffees"> Cafés</option>
                                <option {{ old('type') == 'health' ? 'selected' : '' }} value="health"> Santé & SPA</option>
                            </select>
                            @error('type') <small class="text-danger">{{ $message }}</small> @enderror
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Address</label>
                            <textarea name="address" class="form-control @error('address') is-invalid @enderror" rows="5" style="resize: none">{{ old('address') }}</textarea>
                            @error('address') <small class="text-danger">{{ $message }}</small> @enderror
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Avatar</label>
                            <input type="file" name="avatar" class="form-control">
                            @error('avatar') <small class="text-danger">{{ $message }}</small> @enderror
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Cover</label>
                            <input type="file" name="cover" class="form-control">
                            @error('cover') <small class="text-danger">{{ $message }}</small> @enderror
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="card mt-2">
            <div class="card-header">
                <h5>Geolocation</h5>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        <div id="map" class="d-block" style="width: 100%; height: 540px"></div>
                        <input type="hidden" name="location" id="location" value="{{ old('location') }}">
                    </div>
                    <div class="col-md-6 mt-2">
                        <label>Latitude</label>
                        <input type="text" readonly class="form-control" id="lat" value="{{ explode('|' , old('location'))[0] ?? '' }}">
                    </div>
                    <div class="col-md-6 mt-2">
                        <label>Longitude</label>
                        <input type="text" readonly class="form-control" id="lng" value="{{ explode('|' , old('location'))[1] ?? '' }}">
                    </div>
                </div>
                @error('location') <small class="text-danger text-center">{{ $message }}</small> @enderror
            </div>
        </div>
    </form>
@endsection

@section('breadcrumb')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">New City</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item active"><a href="{{ route('admin.dashboard') }}">{{ config('app.name') }}</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('admin.items.index') }}">Items</a></li>
                        <li class="breadcrumb-item">New Item</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
@endsection

@section('script')
    <script src="{{ asset('plugins/bs-custom-file-input/bs-custom-file-input.min.js') }}"></script>
    <script src="{{ asset('plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ asset('plugins/select2/js/select2.full.min.js') }}"></script>
@endsection

@section('js')
    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true,
                "autoWidth": false,
                "ordering": false,
            });
        });
        $(document).ready(function () {
            bsCustomFileInput.init();
        });
        $('.select2bs4').select2({
            theme: 'bootstrap4'
        })
        var map;
        function initMap() {
                @if($errors->any() && old('location') != null) var location = { lat : {{ explode('|',old('location'))[0] }} , lng : {{ explode('|',old('location'))[1] }} };
                @else var location = {lat: 30.9431046, lng: -6.9752925 };  @endif

                map = new google.maps.Map(document.getElementById('map'), {
                center: location,
                zoom: 8
            });
            google.maps.event.addListener(map, 'click', function(event) {
                removeMarkers()
                placeMarker(event.latLng);
                $('#location').val(event.latLng.lat() +'|' + event.latLng.lng() )
                $('#lat').val(event.latLng.lat())
                $('#lng').val(event.latLng.lng())
            });
            var gmarkers = [];
            function placeMarker(location) {
                var marker = new google.maps.Marker({
                    position: location,
                    map: map
                });
                gmarkers.push(marker);
            }
            function removeMarkers(){
                for(i=0; i<gmarkers.length; i++){
                    gmarkers[i].setMap(null);
                }
            }
        }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBheVz-S_cHHNu_ZQWlCKGJKXOK1-s13k8&callback=initMap"
            async defer></script>
@endsection
@section('style')
    <link rel="stylesheet" href="{{ asset('plugins/select2/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ asset('plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">
@endsection

resources/views/admin/items/edit.blade.php
@php $link = 'items';@endphp
@extends('admin.layout')
@section('title') Item {{ $item->name }} @endsection

@section('content')
    <div class="d-flex justify-content-end">
        <button form="store" class="btn btn-primary btn-sm mr-2"><i class="fa fa-save"></i></button>
    </div>
    <form action="{{ route('admin.items.update' , ['item' => $item->id]) }}" method="post" id="store" enctype="multipart/form-data">
        @csrf @method('PUT')
        <input type="hidden" name="item" value="{{ $item->id }}">
        <div class="card mt-2">
            <div class="card-header">
                <h5 class="card-title">General</h5>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Name:</label>
                            <input type="text" name="name" value="{{ $item->name }}" class="form-control @error('name') is-invalid @enderror">
                            @error('name') <small class="text-danger">{{ $message }}</small> @enderror
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>City</label>
                            <select name="city" class="form-control select2bs4 @error('city') is-invalid @enderror" style="width: 100%;">
                                <option selected disabled>City</option>
                                <option {{ $item->city == 'casa' ? 'selected' : '' }} value="casa"> Casablanca</option>
                                <option {{ $item->city == 'marrakech' ? 'selected' : '' }} value="marrakech"> Marrakech</option>
                                <option {{ $item->city == 'rabat' ? 'selected' : '' }} value="rabat"> Rabat</option>
                                <option {{ $item->city == 'tangier' ? 'selected' : '' }} value="tangier"> Tanger</option>
                                <option {{ $item->city == 'agadir' ? 'selected' : '' }} value="tangier"> Agadir</option>
                                <option {{ $item->city == 'fes' ? 'selected' : '' }} value="tangier"> Fes</option>
                                <option {{ $item->city == 'ouarzazate' ? 'selected' : '' }} value="tangier"> Ouarzazate</option>
                                <option {{ $item->city == 'essaouira' ? 'selected' : '' }} value="tangier"> Essaouira</option>
                            </select>
                            @error('city') <small class="text-danger">{{ $message }}</small> @enderror
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Type</label>
                            <select name="type" class="form-control select2bs4 @error('type') is-invalid @enderror" style="width: 100%;">
                                <option selected disabled>Type</option>
                                <option {{ $item->type == 'activities' ? 'selected' : '' }} value="activities"> Activité</option>
                                <option {{ $item->type == 'restaurants' ? 'selected' : '' }} value="restaurants"> Restaurant</option>
                                <option {{ $item->type == 'hotels' ? 'selected' : '' }} value="hotels"> Hôtel</option>
                                <option {{ $item->type == 'coffees' ? 'selected' : '' }} value="remains"> Cafés</option>
                                <option {{ $item->type == 'health' ? 'selected' : '' }} value="coffees"> Santé & SPA</option>
                            </select>
                            @error('type') <small class="text-danger">{{ $message }}</small> @enderror
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Address</label>
                            <textarea name="address" class="form-control @error('address') is-invalid @enderror" rows="5" style="resize: none">{{ $item->address }}</textarea>
                            @error('address') <small class="text-danger">{{ $message }}</small> @enderror
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Avatar</label>
                            <input type="file" name="avatar" class="form-control">
                            @error('avatar') <small class="text-danger">{{ $message }}</small> @enderror
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Cover</label>
                            <input type="file" name="cover" class="form-control">
                            @error('cover') <small class="text-danger">{{ $message }}</small> @enderror
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="card mt-2">
            <div class="card-header">
                <h5>Geolocation</h5>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        <div id="map" class="d-block" style="width: 100%; height: 540px"></div>
                        <input type="hidden" name="location" id="location" value="{{ $item->location }}">
                    </div>
                    <div class="col-md-6 mt-2">
                        <label>Latitude</label>
                        <input type="text" readonly class="form-control" id="lat" value="{{ explode('|' , $item->location)[0] ?? '' }}">
                    </div>
                    <div class="col-md-6 mt-2">
                        <label>Longitude</label>
                        <input type="text" readonly class="form-control" id="lng" value="{{ explode('|' , $item->location)[1] ?? '' }}">
                    </div>
                </div>
                @error('location') <small class="text-danger text-center">{{ $message }}</small> @enderror
            </div>
        </div>
    </form>
@endsection

@section('breadcrumb')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">New City</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item active"><a href="{{ route('admin.dashboard') }}">{{ config('app.name') }}</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('admin.items.index') }}">Items</a></li>
                        <li class="breadcrumb-item">New Item</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
@endsection

@section('script')
    <script src="{{ asset('plugins/bs-custom-file-input/bs-custom-file-input.min.js') }}"></script>
    <script src="{{ asset('plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ asset('plugins/select2/js/select2.full.min.js') }}"></script>
@endsection

@section('js')
    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true,
                "autoWidth": false,
                "ordering": false,
            });
        });
        $(document).ready(function () {
            bsCustomFileInput.init();
        });
        $('.select2bs4').select2({
            theme: 'bootstrap4'
        })
        var map;
        function initMap() {
            var location = {lat: {{ explode('|' , $item->location)[0] }}, lng: {{ explode('|' , $item->location)[1] }} };

                map = new google.maps.Map(document.getElementById('map'), {
                center: location,
                zoom: 8
            });
            google.maps.event.addListener(map, 'click', function(event) {
                removeMarkers()
                placeMarker(event.latLng);
                $('#location').val(event.latLng.lat() +'|' + event.latLng.lng() )
                $('#lat').val(event.latLng.lat())
                $('#lng').val(event.latLng.lng())
            });
            var gmarkers = [];
            var marker = new google.maps.Marker({
                position: location,
                map: map
            });
            gmarkers.push(marker);
            function placeMarker(location) {
                var marker = new google.maps.Marker({
                    position: location,
                    map: map
                });
                gmarkers.push(marker);
            }
            function removeMarkers(){
                for(i=0; i<gmarkers.length; i++){
                    gmarkers[i].setMap(null);
                }
            }
        }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBheVz-S_cHHNu_ZQWlCKGJKXOK1-s13k8&callback=initMap"
            async defer></script>
@endsection
@section('style')
    <link rel="stylesheet" href="{{ asset('plugins/select2/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ asset('plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">
@endsection

resources/views/admin/items/index.blade.php
@php $link = 'items'; @endphp

@extends('admin.layout')

@section('title') Items @endsection

@section('content')
    <div class="d-flex justify-content-end">
        <a href="{{ route('admin.items.create') }}" class="btn btn-primary btn-sm mr-2"><i class="fa fa-plus-square"></i></a>
        <a href="" class="btn btn-info btn-sm"><i class="fa fa-chart-area"></i></a>
    </div>
    <div class="card mt-2">
        <div class="card-body">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Type</th>
                    <th>City</th>
                    <th>Address</th>
                    <th>Status</th>
                    <th>created at</th>
                    <th>last update</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach($items as $item)
                    <tr>
                        <td>{{ $item->name }}</td>
                        <td class="text-capitalize">{{ $item->type }}</td>
                        <td>{{ $item->city }}</td>
                        <td>{{ $item->address }}</td>
                        <td>
                            @if($item->active) <span class="badge badge-success">Active</span> @else
                                <span class="badge badge-danger">Deactivate</span>
                            @endif
                        </td>
                        <td>{{ date('d/m/Y' , strtotime($item->created_at)) }}</td>
                        <td>{{ date('d/m/Y' , strtotime($item->updated_at)) }}</td>
                        <td>
                            <div class="dropdown d-flex justify-content-center">
                                <a class="nav-link" data-toggle="dropdown">
                                    <i class="fa fa-list"></i>
                                </a>
                                <div class="dropdown-menu dropdown-menu-items dropdown-menu-right text-center">
                                    <a href="{{ route('admin.items.show' , ['item' => $item->id]) }}" class="dropdown-item">
                                        <i class="fas fa-info mr-2"></i> Infos
                                    </a>
                                        <a href="{{ route('admin.items.edit' , ['item' => $item->id]) }}" class="dropdown-item">
                                            <i class="fas fa-edit mr-2"></i> Edit
                                        </a>
                                        <a href="{{ route('admin.items.activate' , ['id' => $item->id]) }}" class="dropdown-item">
                                            <i class="fas {{ $item->active ? 'fa-stop-circle' : 'fa-check' }}"></i> {{ $item->active ? 'Deactivate' : 'Active' }}
                                        </a>
                                        <button form="#delete" onclick="if( confirm('are you sure')) $('#delete').submit()" class="dropdown-item">
                                            <i class="fas fa-trash mr-2"></i> Delete
                                            <form action="{{ route('admin.items.destroy' , ['item' => $item->id]) }}" method="post" id="delete">@csrf @method('DELETE')</form>
                                        </button>
                                </div>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

@section('breadcrumb')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Items</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item active">{{ config('app.name') }}</li>
                        <li class="breadcrumb-item"><a href="{{ route('admin.items.index') }}">Items</a></li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

@endsection

@section('script')
    <script src="{{ asset('plugins/chart.js/Chart.min.js') }}"></script>
    <script src="{{ asset('plugins/chart.js/Chart.min.js') }}"></script>
    <script src="{{ asset('dist/js/demo.js') }}"></script>
    <script src="{{ asset('dist/js/pages/dashboard3.js') }}"></script>
@endsection

@section('js')
    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true,
                "autoWidth": false,
                "ordering": false,
            });
            @if(session()->has('add')) toastr.info('You have been added the item {{ session()->get('update') }}.') @endif
            @if(session()->has('destroy')) toastr.warning('You have been deleted the item {{ session()->get('destroy') }}.')  @endif
        });
        $(document).ready(function () {
            bsCustomFileInput.init();
        });
    </script>
@endsection

@section('style')

@endsection