routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::middleware('admin.guest')->group(function (){
    Route::get('/' , 'LoginController@form')->name('login.form');
    Route::post('/' , 'LoginController@attempt')->name('login');
});

Route::middleware('admin.connected')->group(function (){
    Route::get('dashboard' , 'DashboardController@index')->name('dashboard');

    Route::get('logout' , function (){
        \Illuminate\Support\Facades\Auth::guard('admin')->logout();
        return redirect()->route('admin.login.form');
    })->name('logout');
    Route::resources([
        'items' => 'ItemsController',
        'offers' => 'OffersController',
        'users' => 'UsersController',
        'reservations' => 'ReservationsController'
    ]);
    Route::resource('settings' , 'SettingsController')->only('index' , 'update');
    Route::get('/items/activate/{id}' , 'ItemsController@activate')->name('items.activate');
    Route::get('/offers/activate/{id}' , 'OffersController@activate')->name('offers.activate');
    Route::get('/offers/sponsor/{id}' , 'OffersController@sponsored')->name('offers.sponsor');
    Route::get('/reservations/read/{id}' , 'ReservationsController@toggleRead')->name('reservations.read');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::namespace('Landing')->group(function (){
    Route::get('/','OffersController@index')->name('landing.index');
    Route::get('offers/{type?}','OffersController@index')->name('landing.type');
    Route::group(['prefix' => 'offers' ,'as' => 'landing.'] , function (){
        Route::get('show/{id}' , 'OffersController@show')->name('show');
        Route::post('search' , 'OffersController@search')->name('search');
        Route::post('query' , 'OffersController@query')->name('query');
    });
    Route::resource('comments' , 'CommentsController')->only('store');
    Route::resource('impressions' , 'ImpressionsController')->only('store');
});

Route::middleware('guest') ->group(function (){
    Route::view('login' , 'clients.login')->name('login.form');
    Route::post('login' , 'Auth\LoginController@attempt')->name('login');
    Route::view('register' , 'clients.register')->name('register.form');
    Route::post('register' , 'Auth\RegisterController@attempt')->name('register');
});
Route::get('logout' , function (){
    \Illuminate\Support\Facades\Auth::logout();
    return redirect('/');
})->name('logout');

app/User.php
<?php

namespace App;

use App\Entries\Comment;
use App\Entries\Impression;
use App\Entries\Reservation;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [
        'id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'active' => 'boolean'
    ];

    public function getFullNameAttribute(){
        return $this->last_name . ' '.$this->first_name;
    }

    public function reservations(){
        return $this->hasMany(Reservation::class);
    }

    public function impressions(){
        return $this->hasMany(Impression::class);
    }

    public function comments(){
        return $this->hasMany(Comment::class);
    }

}

app/Http/Controllers/Admin/SettingsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Admin;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class SettingsController extends Controller
{
    public function index(){
        return view('admin.settings.index' , ['user' => Auth::guard('admin')->user()]);
    }

    public function update($id ,Request $request){
        $this->validate($request , [
            'name' => 'required|string',
            'email' => 'required|string|email',
            'password' => 'nullable|string|confirmed',
        ]);

        $admin = Admin::all()->find(Auth::guard('admin')->id());
        $admin->update([
            'name' => $request->name,
            'password' => isset($request->password) ? Hash::make($request->password) : $admin->password ,
            'email' => $request->email
        ]);
        return isset($request->password) ? redirect()->route('admin.logout') : back();
    }
}

app/Http/Controllers/Client/ReservationsController.php
<?php

namespace App\Http\Controllers\Client;

use App\Contracts\IReservations;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use phpDocumentor\Reflection\DocBlock\Tags\Version;

class ReservationsController extends Controller
{
    private $reservations;

    public function __construct(IReservations $reservations)
    {
        $this->reservations = $reservations;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('clients.reservations.index' , ['reservations' => $this->reservations->listByCurrentUser()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request , [
            'date' => 'required|date|after:'.date('Y-m-d'),
            'members' => 'required|numeric|min:1'
        ]);
        $reservation = $this->reservations->create($request->all());
        return redirect()->route('clients.reservations.show' , ['reservation' => $reservation->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('clients.reservations.show' , ['reservation' => $this->reservations->find($id)]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Client/SettingsController.php
<?php

namespace App\Http\Controllers\Client;

use App\Contracts\IUsers;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class SettingsController extends Controller
{
    private $users;

    public function __construct(IUsers $users)
    {
        $this->users = $users;
    }

    public function index(){
        return view('clients.settings.index' , ['user' => Auth::user()]);
    }

    public function update(Request $request){
        $this->users->update(Auth::id() , $request->all());
        return isset($request->password) ? redirect()->route('login.form') : back();
    }
}

resources/views/clients/settings/index.blade.php
@php $link = 'settings' @endphp
@extends('clients.layout')

@section('title') Paramètres @endsection

@section('content')
    <div class="d-flex justify-content-end">
        <button form="update" class="btn btn-sm btn-primary"><i class="fa fa-save"></i></button>
    </div>
    <div class="card mt-2">
        <div class="card-header">
            {{ $user->full_name }}
        </div>
        <div class="card-body">
            <form action="{{ route('clients.settings.update' , ['setting' => -1]) }}" method="post" id="update">
                @csrf   @method('PUT')
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Nom</label>
                            <input type="text" class="form-control @error('last_name') is-invalid @enderror" value="{{ $user->last_name }}" name="last_name">
                            @error('last_name') <small class="text-center text-danger btn-block mt-2">{{ $message }}</small> @enderror
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Prénom</label>
                            <input type="text" class="form-control @error('first_name') is-invalid @enderror" value="{{ $user->first_name }}" name="first_name">
                            @error('first_name') <small class="text-center text-danger btn-block mt-2">{{ $message }}</small> @enderror
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Prénom</label>
                            <input type="text" class="form-control @error('email') is-invalid @enderror" value="{{ $user->email }}" name="email">
                            @error('email') <small class="text-center text-danger btn-block mt-2">{{ $message }}</small> @enderror
                        </div>
                    </div>
                    <div class="col-md-6"></div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Mot de passe</label>
                            <input type="password" class="form-control @error('password') is-invalid @enderror" name="password">
                            @error('password') <small class="text-center text-danger btn-block mt-2">{{ $message }}</small> @enderror
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Confirmation du mot de passe</label>
                            <input type="password" class="form-control @error('password_confirmation') is-invalid @enderror" name="password_confirmation">
                            @error('password_confirmation') <small class="text-center text-danger btn-block mt-2">{{ $message }}</small> @enderror
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    @endsection

@section('breadcrumb')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Paramètres</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item active">{{ config('app.name') }}</li>
                        <li class="breadcrumb-item"><a href="{{ route('clients.settings.index') }}">Paramères</a></li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
@endsection